import { Category, Restaurant, Food, Coupon, PaymentMethodConfig, SystemSettings, Banner, DeliveryRider, Review, AppNotification, UserProfile } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-biryani',
    name: 'Biryani & Rice',
    slug: 'biryani-rice',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&auto=format&fit=crop&q=80',
    description: 'Authentic Kacchi, Tehari, Polao and fragrant rice dishes.',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'cat-burgers',
    name: 'Gourmet Burgers',
    slug: 'gourmet-burgers',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&auto=format&fit=crop&q=80',
    description: 'Juicy smashed beef and crispy fried chicken burgers.',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'cat-pizza',
    name: 'Wood-Fired Pizza',
    slug: 'wood-fired-pizza',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=500&auto=format&fit=crop&q=80',
    description: 'Freshly baked stone-oven pizzas loaded with cheese.',
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 'cat-snacks',
    name: 'Snacks & Starters',
    slug: 'snacks-starters',
    imageUrl: 'https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=500&auto=format&fit=crop&q=80',
    description: 'Fries, wings, samosas and quick bites.',
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 'cat-drinks',
    name: 'Drinks & Desserts',
    slug: 'drinks-desserts',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
    description: 'Cold coffee, Mango Lassi, Falooda, and sweet treats.',
    isActive: true,
    sortOrder: 5,
  },
];

export const INITIAL_RESTAURANTS: Restaurant[] = [
  {
    id: 'rest-kacchi-express',
    name: 'Kacchi Express',
    slug: 'kacchi-express',
    description: 'Premium Old Dhaka style Basmati Mutton Kacchi & Borhani.',
    logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1000&auto=format&fit=crop&q=80',
    cuisineTypes: ['Biryani', 'Traditional', 'Bengali'],
    address: 'Dhanmondi Road 27, Dhaka',
    phone: '+8801711223344',
    rating: 4.8,
    reviewCount: 342,
    deliveryFee: 60,
    minimumOrder: 250,
    estimatedDeliveryTime: 30,
    isOpen: true,
    isFeatured: true,
    status: 'active',
  },
  {
    id: 'rest-dhaka-biryani',
    name: 'Dhaka Biryani House',
    slug: 'dhaka-biryani-house',
    description: 'Rich Zafrani Beef Tehari and Shahi Chicken Roast.',
    logoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=1000&auto=format&fit=crop&q=80',
    cuisineTypes: ['Tehari', 'Kebab', 'Bengali'],
    address: 'Gulshan 1 Circle, Dhaka',
    phone: '+8801811998877',
    rating: 4.6,
    reviewCount: 210,
    deliveryFee: 50,
    minimumOrder: 200,
    estimatedDeliveryTime: 25,
    isOpen: true,
    isFeatured: true,
    status: 'active',
  },
  {
    id: 'rest-burger-lab',
    name: 'Burger Lab BD',
    slug: 'burger-lab-bd',
    description: 'Craving artisanal smashed beef burgers & loaded fries.',
    logoUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1000&auto=format&fit=crop&q=80',
    cuisineTypes: ['Burgers', 'American', 'Fast Food'],
    address: 'Banani Block 11, Dhaka',
    phone: '+8801911445566',
    rating: 4.7,
    reviewCount: 489,
    deliveryFee: 70,
    minimumOrder: 300,
    estimatedDeliveryTime: 35,
    isOpen: true,
    isFeatured: true,
    status: 'active',
  },
  {
    id: 'rest-pizza-district',
    name: 'Pizza District',
    slug: 'pizza-district',
    description: 'Neapolitan style thin crust pizzas with mozzarella burst.',
    logoUrl: 'https://images.unsplash.com/photo-1579751626657-72bc17010498?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1000&auto=format&fit=crop&q=80',
    cuisineTypes: ['Pizza', 'Italian', 'Pasta'],
    address: 'Uttara Sector 3, Dhaka',
    phone: '+8801611778899',
    rating: 4.5,
    reviewCount: 175,
    deliveryFee: 65,
    minimumOrder: 400,
    estimatedDeliveryTime: 40,
    isOpen: true,
    isFeatured: false,
    status: 'active',
  },
  {
    id: 'rest-chillox-style',
    name: 'Chillox Burger Lounge',
    slug: 'chillox-burger-lounge',
    description: 'Extra cheesy smash patty burgers with signature sauces.',
    logoUrl: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=200&auto=format&fit=crop&q=80',
    coverImageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1000&auto=format&fit=crop&q=80',
    cuisineTypes: ['Burgers', 'Shakes', 'Fast Food'],
    address: 'Mirpur 10 Circle, Dhaka',
    phone: '+8801511223344',
    rating: 4.6,
    reviewCount: 310,
    deliveryFee: 45,
    minimumOrder: 180,
    estimatedDeliveryTime: 25,
    isOpen: true,
    isFeatured: true,
    status: 'active',
  },
];

export const INITIAL_FOODS: Food[] = [
  // Kacchi Express Foods
  {
    id: 'food-mutton-kacchi',
    name: 'Shahi Mutton Kacchi Biryani (Platter)',
    slug: 'shahi-mutton-kacchi-platter',
    description: 'Tender mutton marinated in royal spices, slow-cooked with aromatic Basmati rice, served with Zafrani Aloo & Egg.',
    price: 380,
    discountPrice: 350,
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-biryani',
    restaurantId: 'rest-kacchi-express',
    rating: 4.9,
    reviewCount: 198,
    preparationTime: 20,
    isAvailable: true,
    isFeatured: true,
    tags: ['Best Seller', 'Mutton', 'Rice'],
  },
  {
    id: 'food-special-borhani',
    name: 'Traditional Chilled Borhani (500ml)',
    slug: 'traditional-chilled-borhani',
    description: 'Refreshing yogurt drink spiced with mustard, mint, cumin and green chili.',
    price: 80,
    discountPrice: 70,
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-drinks',
    restaurantId: 'rest-kacchi-express',
    rating: 4.8,
    reviewCount: 120,
    preparationTime: 5,
    isAvailable: true,
    isFeatured: true,
    tags: ['Drink', 'Yogurt'],
  },

  // Dhaka Biryani House Foods
  {
    id: 'food-beef-tehari',
    name: 'Old Dhaka Mustard Oil Beef Tehari',
    slug: 'old-dhaka-beef-tehari',
    description: 'Authentic Chinigura rice cooked with mustard oil, aromatic green chilies and succulent beef cubes.',
    price: 260,
    discountPrice: 240,
    imageUrl: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-biryani',
    restaurantId: 'rest-dhaka-biryani',
    rating: 4.7,
    reviewCount: 145,
    preparationTime: 15,
    isAvailable: true,
    isFeatured: true,
    tags: ['Beef', 'Mustard Oil'],
  },
  {
    id: 'food-chicken-roast',
    name: 'Shahi Chicken Roast with Polao',
    slug: 'shahi-chicken-roast-polao',
    description: 'Fragrant Chinigura Kalijira Polao served with sweet & spicy caramelized chicken roast leg piece.',
    price: 290,
    discountPrice: 270,
    imageUrl: 'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-biryani',
    restaurantId: 'rest-dhaka-biryani',
    rating: 4.8,
    reviewCount: 95,
    preparationTime: 18,
    isAvailable: true,
    isFeatured: false,
    tags: ['Chicken', 'Polao'],
  },

  // Burger Lab BD Foods
  {
    id: 'food-smash-beef-burger',
    name: 'Double Smash Beef Cheese Burger',
    slug: 'double-smash-beef-burger',
    description: 'Two 100% prime beef smash patties, double cheddar cheese, caramelized onions and secret Lab sauce.',
    price: 360,
    discountPrice: 320,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-burgers',
    restaurantId: 'rest-burger-lab',
    rating: 4.9,
    reviewCount: 215,
    preparationTime: 20,
    isAvailable: true,
    isFeatured: true,
    tags: ['Cheesy', 'Beef', 'Top Rated'],
  },
  {
    id: 'food-crispy-chicken-burger',
    name: 'Naga Fried Chicken Crunch Burger',
    slug: 'naga-fried-chicken-burger',
    description: 'Extra crispy buttermilk fried chicken thigh tossed in Naga chili glaze with garlic mayo.',
    price: 310,
    discountPrice: null,
    imageUrl: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-burgers',
    restaurantId: 'rest-burger-lab',
    rating: 4.7,
    reviewCount: 160,
    preparationTime: 15,
    isAvailable: true,
    isFeatured: true,
    tags: ['Spicy', 'Naga', 'Chicken'],
  },
  {
    id: 'food-loaded-fries',
    name: 'Cheesy Loaded Bacon & Beef Fries',
    slug: 'cheesy-loaded-fries',
    description: 'Crispy skin-on fries topped with melted mozzarella, minced beef chili and jalapeno slices.',
    price: 240,
    discountPrice: 210,
    imageUrl: 'https://images.unsplash.com/photo-1576107232684-1279f3908594?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-snacks',
    restaurantId: 'rest-burger-lab',
    rating: 4.6,
    reviewCount: 110,
    preparationTime: 12,
    isAvailable: true,
    isFeatured: false,
    tags: ['Fries', 'Snack'],
  },

  // Pizza District Foods
  {
    id: 'food-supreme-pizza',
    name: '12" Spicy Chicken Supreme Pizza',
    slug: 'spicy-chicken-supreme-pizza',
    description: 'Mozzarella, spicy grilled chicken, bell peppers, black olives, sweet corn and red chili flakes.',
    price: 680,
    discountPrice: 590,
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-pizza',
    restaurantId: 'rest-pizza-district',
    rating: 4.8,
    reviewCount: 140,
    preparationTime: 25,
    isAvailable: true,
    isFeatured: true,
    tags: ['Pizza', 'Chicken', '12 inch'],
  },
  {
    id: 'food-margherita-pizza',
    name: '12" Classic Double Cheese Margherita',
    slug: 'classic-margherita-pizza',
    description: 'San Marzano tomato sauce, double mozzarella, fresh basil leaves and extra virgin olive oil drizzle.',
    price: 520,
    discountPrice: 480,
    imageUrl: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-pizza',
    restaurantId: 'rest-pizza-district',
    rating: 4.5,
    reviewCount: 88,
    preparationTime: 20,
    isAvailable: true,
    isFeatured: false,
    tags: ['Vegetarian', 'Cheese'],
  },

  // Chillox Burger Lounge
  {
    id: 'food-chillox-special',
    name: 'Chillox Monster Tower Burger',
    slug: 'chillox-monster-tower-burger',
    description: 'Triple patty (beef + chicken patty + crispy cheese wheel), onion rings, thousand island dressing.',
    price: 450,
    discountPrice: 399,
    imageUrl: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-burgers',
    restaurantId: 'rest-chillox-style',
    rating: 4.8,
    reviewCount: 230,
    preparationTime: 22,
    isAvailable: true,
    isFeatured: true,
    tags: ['Monster', 'Huge', 'Cheesy'],
  },
  {
    id: 'food-mango-lassi',
    name: 'Special Rajshahi Mango Lassi',
    slug: 'special-rajshahi-mango-lassi',
    description: 'Thick creamy yogurt blended with real sweet Rajshahi mango pulp and crushed ice.',
    price: 130,
    discountPrice: 110,
    imageUrl: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop&q=80',
    categoryId: 'cat-drinks',
    restaurantId: 'rest-kacchi-express',
    rating: 4.9,
    reviewCount: 175,
    preparationTime: 5,
    isAvailable: true,
    isFeatured: true,
    tags: ['Mango', 'Drink', 'Dessert'],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'coupon-welcome50',
    code: 'WELCOME50',
    discountType: 'fixed',
    discountValue: 100,
    minimumOrder: 300,
    usageLimit: 1000,
    usedCount: 42,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'coupon-bmfest20',
    code: 'BMFEST20',
    discountType: 'percentage',
    discountValue: 20, // 20%
    minimumOrder: 400,
    maximumDiscount: 150,
    usageLimit: 500,
    usedCount: 88,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
  {
    id: 'coupon-biryani',
    code: 'BMBIRYANI',
    discountType: 'fixed',
    discountValue: 50,
    minimumOrder: 250,
    usageLimit: 200,
    usedCount: 19,
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    isActive: true,
  },
];

export const INITIAL_PAYMENT_METHODS: PaymentMethodConfig[] = [
  {
    id: 'pm-cod',
    name: 'Cash on Delivery',
    type: 'cod',
    instructions: 'Pay in cash directly to our delivery rider upon receiving your hot food order.',
    isEnabled: true,
    sortOrder: 1,
  },
  {
    id: 'pm-bkash',
    name: 'bKash Manual Payment',
    type: 'manual',
    accountNumber: '01711223344',
    instructions: 'Send money to bKash Merchant/Personal number 01711223344 and paste your 10-character Transaction ID below.',
    isEnabled: true,
    sortOrder: 2,
  },
  {
    id: 'pm-nagad',
    name: 'Nagad Manual Payment',
    type: 'manual',
    accountNumber: '01811998877',
    instructions: 'Send money via Nagad App to 01811998877 and provide your Transaction ID for fast manual approval.',
    isEnabled: true,
    sortOrder: 3,
  },
  {
    id: 'pm-rocket',
    name: 'Rocket Manual Payment',
    type: 'manual',
    accountNumber: '01911445566-7',
    instructions: 'Send money to Rocket number 01911445566-7 and enter transaction reference.',
    isEnabled: true,
    sortOrder: 4,
  },
  {
    id: 'pm-gateway',
    name: 'Online Payment Gateway (SSLCommerz / Bkash API)',
    type: 'gateway',
    instructions: 'Pay instantly via credit card, debit card, or automated mobile banking portal.',
    isEnabled: true,
    sortOrder: 5,
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  id: 'general',
  businessName: 'BM Food Express',
  logoUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=150&auto=format&fit=crop&q=80',
  contactPhone: '+8809612345678',
  contactEmail: 'support@bmfood.com',
  currency: '৳',
  taxPercentage: 5, // 5% VAT
  defaultDeliveryFee: 50,
  minimumOrder: 150,
  codEnabled: true,
  manualPaymentsEnabled: true,
  onlineGatewayEnabled: true,
};

export const INITIAL_BANNERS: Banner[] = [
  {
    id: 'banner-1',
    title: '50% OFF On First Kacchi Order',
    subtitle: 'Taste authentic Old Dhaka Shahi Mutton Kacchi with code WELCOME50',
    imageUrl: 'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/restaurant/rest-kacchi-express',
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 'banner-2',
    title: 'Double Smash Burger Extravaganza',
    subtitle: 'Burger Lab BD juicy double patties delivered hot to your doorstep',
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/restaurant/rest-burger-lab',
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 'banner-3',
    title: 'Fast 25-Min Hot Food Delivery',
    subtitle: 'Free delivery on orders over ৳500 with BM Food Express',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=1200&auto=format&fit=crop&q=80',
    linkUrl: '/restaurants',
    isActive: true,
    sortOrder: 3,
  },
];

export const INITIAL_RIDERS: DeliveryRider[] = [
  {
    id: 'rider-rahim',
    name: 'Rahim Uddin (Hero Rider)',
    phone: '+8801700112233',
    vehicleType: 'bike',
    vehicleNumber: 'Dhaka Metro HA-1234',
    status: 'available',
    totalDeliveries: 142,
    rating: 4.9,
    walletEarnings: 12500,
    isApproved: true,
  },
  {
    id: 'rider-karim',
    name: 'Karim Miah',
    phone: '+8801800223344',
    vehicleType: 'scooter',
    vehicleNumber: 'Dhaka Metro LA-5678',
    status: 'available',
    totalDeliveries: 89,
    rating: 4.8,
    walletEarnings: 8200,
    isApproved: true,
  },
  {
    id: 'rider-jamal',
    name: 'Jamal Hossain',
    phone: '+8801900334455',
    vehicleType: 'bicycle',
    status: 'offline',
    totalDeliveries: 45,
    rating: 4.7,
    walletEarnings: 3900,
    isApproved: true,
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    rating: 5,
    comment: 'The Mutton Kacchi was extraordinarily soft and full of Zafrani aroma! Delivery took only 22 minutes.',
    restaurantId: 'rest-kacchi-express',
    restaurantName: 'Kacchi Express',
    foodId: 'food-mutton-kacchi',
    foodName: 'Shahi Mutton Kacchi Biryani (Platter)',
    userId: 'cust-demo-1',
    userName: 'Tanvir Ahmed',
    orderId: 'ord-demo-1',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rev-2',
    rating: 5,
    comment: 'Best smash burger in Banani! Juice was bursting out and cheese was melted perfectly.',
    restaurantId: 'rest-burger-lab',
    restaurantName: 'Burger Lab BD',
    foodId: 'food-smash-beef-burger',
    foodName: 'Double Smash Beef Cheese Burger',
    userId: 'cust-demo-2',
    userName: 'Nusrat Jahan',
    orderId: 'ord-demo-2',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-1',
    userId: 'all',
    title: '🎉 Welcome to BM Food Express!',
    message: 'Get 50% discount on your first order using code WELCOME50 at checkout!',
    targetAudience: 'all',
    isRead: false,
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    uid: 'admin-main',
    name: 'BM Food System Admin',
    email: 'admin@example.com',
    phone: '+8801700000000',
    photoURL: null,
    role: 'admin',
    status: 'active',
    addresses: [
      {
        id: 'addr-admin',
        name: 'Admin HQ',
        phone: '+8801700000000',
        address: 'Gulshan 2, Dhaka',
        city: 'Dhaka',
        area: 'Gulshan',
        isDefault: true,
      },
    ],
    favorites: [],
    walletBalance: 5000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'user-bornil',
    name: 'Bornil Mahmud (Super Admin)',
    email: 'bornilmahmud56@gmail.com',
    phone: '+8801812345678',
    photoURL: null,
    role: 'admin',
    status: 'active',
    addresses: [],
    favorites: [],
    walletBalance: 10000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'cust-demo-1',
    name: 'Tanvir Ahmed (Customer)',
    email: 'tanvir@example.com',
    phone: '+8801711998877',
    photoURL: null,
    role: 'customer',
    status: 'active',
    addresses: [
      {
        id: 'addr-cust-1',
        name: 'Tanvir Ahmed',
        phone: '+8801711998877',
        address: 'House 14, Road 7, Block F',
        city: 'Dhaka',
        area: 'Dhanmondi',
        isDefault: true,
      },
    ],
    favorites: ['food-mutton-kacchi'],
    walletBalance: 500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'vendor-kacchi',
    name: 'Kacchi Express Manager',
    email: 'vendor.kacchi@bmfood.com',
    phone: '+8801711223344',
    photoURL: null,
    role: 'restaurant',
    status: 'active',
    restaurantId: 'rest-kacchi-express',
    addresses: [],
    favorites: [],
    walletBalance: 25000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    uid: 'rider-rahim-user',
    name: 'Rahim Uddin (Delivery Hero)',
    email: 'rider.rahim@bmfood.com',
    phone: '+8801700112233',
    photoURL: null,
    role: 'rider',
    status: 'active',
    addresses: [],
    favorites: [],
    walletBalance: 12500,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];


